version: "3.8"
services:
   python_server:
    container_name: python_server
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/code
    ports:
      - 1337:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

   celery:
    container_name: celery
    build: ./
    command: celery -A server.celery worker --loglevel=DEBUG --logfile=./logs/celery.log
    volumes:
      - ./Backend:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - python_server
      - redis

   redis:
    container_name: redis
    image: redis:6-alpine

   celery_flower:
    container_name: celery-flower
    build: 
      context: ./
    command:  celery -A celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - python_server
      - redis
      - celery