version: "3"
services:
   python_server:
    container_name: python_server
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend:/code
    ports:
      - 8000:8000
    expose:
      - 8000
   